language: python

services:
  - docker

before_install:
  - docker build -t flopyarcade/master --no-cache -f Dockerfile .

install:
  - docker run -p 81:81 flopyarcade/master python3 -m pip install codecov coverage

script:
  - docker run -p 81:81 flopyarcade/master python3 /FloPyArcade/test_FloPyArcade.py

after_success:
  - docker run -p 81:81 flopyarcade/master codecov --token="5243a254-feca-4875-ba8d-b09deb44981d"
  - docker run -p 81:81 flopyarcade/master bash <(curl -s https://codecov.io/bash)
