language: python

services:
  - docker

before_install:
  - docker build -t flopyarcade/master --no-cache -f Dockerfile .

script:
  - docker run -p 81:81 flopyarcade/master /bin/sh -c "apt-get install -y git; apt-get install -y hg; python3 -m pip install codecov coverage; python3 -m coverage run /FloPyArcade/test_FloPyArcade.py; codecov -t 5243a254-feca-4875-ba8d-b09deb44981d"
