language: python

services:
  - docker

before_install:
  - docker build -t flopyarcade/master --no-cache -f Dockerfile .

script:
  - docker run -p 81:81 flopyarcade/master python3 /FloPyArcade/test_FloPyArcade.py
  - name: Coveralls GitHub Action
    uses: FloPyArcade/github-action@master
