# -*- mode: python ; coding: utf-8 -*-

import sys
sys.setrecursionlimit(5000)

block_cipher = None


excludes = [
            # 'collections',
            # 'ctypes',
            # 'dateutil',
            # 'distutils',
            # 'email',
            # 'encodings',
            # 'flopy',
            # 'http',
            # 'importlib',
            # 'json',
            # 'logging',
            # 'matplotlib',
            # 'numpy',
            # 'tkinter',
            # 'unittest',
            # 'urllib',

            # '_pytest',
            'asciitree',
            'asyncio',
            'atomicwrites',
            'attr',
            'babel',
            'backcall',
            'bcolz',
            'blosc',
            'bokeh',
            'botocore',
            'bottleneck',
            'bs4',
            'bson',
            'ccplot.algorithms',
            'certifi',
            'cffi',
            'cftime',
            'chardet',
            'click',
            'cloudpickle',
            'colorama',
            'concurrent',
            'curses',
            'cvxopt',
            'cyordereddict',
            'Cython',
            'cytoolz',
            'dask',
            'dbm',
            'defusedxml',
            'descartes',
            # 'dill',
            'distributed',
            'docrepr',
            'docutils',
            'fasteners',
            'fastparquet',
            'feather',
            'funcsigs',
            'future',
            'graphviz',
            'h5py',
            'html',
            'html5lib',
            'idna',
            'ipykernel',
            'ipyparallel',
            'IPython',
            'ipython_genutils',
            'ipywidgets',
            'jedi',
            'jinja2',
            'joblib',
            'jsonschema',
            'jupyter_client',
            'jupyter_core',
            'keras',
            'Levenshtein',
            'lib2to3',
            'llvmlite',
            'locket',
            'lxml',
            'markupsafe',
            'more_itertools',
            'msgpack',
            # 'multiprocessing',
            'nbconvert',
            'nbformat',
            'netCDF4',
            'notebook',
            'numba',
            'numcodecs',
            'numdifftools',
            'numexpr',
            'numpydoc',
            'packaging',
            'pandas',
            'pandas_datareader',
            'parso',
            'partd',
            'patsy',
            'PIL',
            'pkg_resources',
            'pluggy',
            'prometheus_client',
            'prompt_toolkit',
            'psutil',
            'py',
            'pyarrow',
            'pycparser',
            'pydoc_data',
            'pygments',
            'PyQT'
            'PyQt5',
            'pytz',
            'pyximport',
            'qtpy',
            'requests',
            'scipy',
            'seaborn',
            'selenium',
            'send2trash',
            'setuptools',
            'simplejson',
            'shapely',
            'sklearn',
            'snappy',
            'sortedcontainers',
            'sphinx',
            'sqlalchemy',
            'sqlite3',
            'statsmodels',
            'tables',
            'tblib',
            # 'tensorboard',
            # 'tensorflow',
            'terminado',
            'test',
            'testpath',
            'thrift',
            'toolz',
            'torch',
            'tornado',
            'traitlets',
            'urllib3',
            'wcwidth',
            'webencodings',
            'win32com',
            'winpty',
            'wsgiref',
            'xarray',
            'xlrd',
            'xlsxwriter',
            'xml',
            'xmlrpc',
            'yaml',
            'zarr',
            'zict',
            'zmq',
            ]

a = Analysis(['FloPyArcadePlay.py'],
             pathex=['C:\\FloPyArcade'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=excludes,
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='FloPyArcadePlay',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False )
