import os
import sys
import matplotlib
# import tensorflow
from cx_Freeze import setup, Executable

# https://stackoverflow.com/questions/35533803/keyerror-tcl-library-when-i-use-cx-freeze
import os.path
PYTHON_INSTALL_DIR = os.path.dirname(os.path.dirname(os.__file__))
os.environ['TCL_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tcl8.6')
os.environ['TK_LIBRARY'] = os.path.join(PYTHON_INSTALL_DIR, 'tcl', 'tk8.6')

# https://stackoverflow.com/questions/27281317/cx-freeze-preventing-including-unneeded-packages
# https://stackoverflow.com/questions/5523867/hide-console-window-with-tkinter-and-cx-freeze/11374527


excludes = [
            # 'collections',
            # 'ctypes',
            # 'dateutil',
            # 'distutils',
            # 'email',
            # 'encodings',
            # 'flopy',
            # 'http',
            # 'importlib',
            # 'json',
            # 'logging',
            # 'matplotlib',
            # 'numpy',
            # 'tkinter',
            # 'unittest',
            # 'urllib',

            '_pytest',
            'asciitree',
            'asyncio',
            'atomicwrites',
            'attr',
            'babel',
            'backcall',
            'bcolz',
            'blosc',
            'bokeh',
            'botocore',
            'bottleneck',
            'bs4',
            'bson',
            'ccplot.algorithms',
            'certifi',
            'cffi',
            'cftime',
            'chardet',
            'click',
            'cloudpickle',
            'colorama',
            'concurrent',
            'curses',
            'cvxopt',
            'cyordereddict',
            'Cython',
            'cytoolz',
            'dask',
            'dbm',
            'defusedxml',
            'descartes',
            # 'dill',
            'distributed',
            'docrepr',
            'docutils',
            'fasteners',
            'fastparquet',
            'feather',
            'funcsigs',
            'future',
            'graphviz',
            'h5py',
            'html',
            'html5lib',
            'idna',
            'ipykernel',
            'ipyparallel',
            'IPython',
            'ipython_genutils',
            'ipywidgets',
            'jedi',
            'jinja2',
            'joblib',
            'jsonschema',
            'jupyter_client',
            'jupyter_core',
            'keras',
            'Levenshtein',
            'lib2to3',
            'llvmlite',
            'locket',
            'lxml',
            'markupsafe',
            'more_itertools',
            'msgpack',
            # 'multiprocessing',
            'nbconvert',
            'nbformat',
            'netCDF4',
            'notebook',
            'numba',
            'numcodecs',
            'numdifftools',
            'numexpr',
            'numpydoc',
            'packaging',
            'pandas',
            'pandas_datareader',
            'parso',
            'partd',
            'patsy',
            'PIL',
            'pkg_resources',
            'pluggy',
            'prometheus_client',
            'prompt_toolkit',
            'psutil',
            'py',
            'pyarrow',
            'pycparser',
            'pydoc_data',
            'pygments',
            'PyQT'
            'PyQt5',
            'pytz',
            'pyximport',
            'qtpy',
            'requests',
            'scipy',
            'seaborn',
            'selenium',
            'send2trash',
            'setuptools',
            'simplejson',
            'sklearn',
            'snappy',
            'sortedcontainers',
            'sphinx',
            'sqlalchemy',
            'sqlite3',
            'statsmodels',
            'tables',
            'tblib',
            # 'tensorboard',
            # 'tensorflow',
            'terminado',
            'test',
            'testpath',
            'thrift',
            'toolz',
            'torch',
            'tornado',
            'traitlets',
            'urllib3',
            'wcwidth',
            'webencodings',
            'win32com',
            'winpty',
            'wsgiref',
            'xarray',
            'xlrd',
            'xlsxwriter',
            'xml',
            'xmlrpc',
            'yaml',
            'zarr',
            'zict',
            'zmq',
            ]

os.chdir('C:\\FloPyArcade\\')

if 'bdist_msi' in sys.argv:
    sys.argv += ['--initial-target-dir', 'C:\\' + 'FloPyArcade',
                 '-O', '-c', '-s',
                 '--target-dir', 'build',
                 'install-dir', 'build\\files']

exe = Executable(
      script="C:\\FloPyArcade\\FloPyArcadePlay.py",
      # base="Win32GUI",   # suppress console or not
      base=None,
      targetName="FloPyArcade.exe"
     )

# https://stackoverflow.com/questions/41735413/from-import-methods-importerror-cannot-import-name-methods-in-cx-freeze-p
build_exe_options = {'includes': ['matplotlib.backends.backend_tkagg', 'numpy.core._methods', 'numpy.lib.format', 'tensorflow'],
                     'include_files': [(matplotlib.get_data_path(), 'mpl-data'),
                                       os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tk86t.dll'),
                                       os.path.join(PYTHON_INSTALL_DIR, 'DLLs', 'tcl86t.dll')],
                     'excludes': excludes,
                     'packages': ['matplotlib'],
                     }

setup(
      name='FloPyArcade.exe',
      options = {'build_exe': build_exe_options},
      version='0.1',
      author='Philipp Hoehn',
      description='FloPyArcade',
      executables=[exe]
      )